class AuthException(Exception):
    pass


class StorageException(Exception):
    pass
